### PR TITLE
Fetch data lazily

### PR DESCRIPTION
**Pull request by theofidry**
This allows phpbrew to instantiate this class and enable/disable an extension without triggering a request to fetch the package data if unnecessary. This way enabling/disabling an extension works offline.

Closes https://github.com/phpbrew/PEARX/issues/7 (not 100% of this)
Closes https://github.com/phpbrew/phpbrew/issues/813 (tested locally)

I also did a few CS changes but I can revert them if you're not happy with them. Tests are failing locally:

```
vendor/bin/phpunit                                                                                                                                                                                                          tfidry@Theos-MBP
PHPUnit 5.7.26 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.10 with Xdebug 2.5.5
Configuration: /Users/tfidry/Project/phpbrew/PEARX/phpunit.xml

...PEAR Channel discover failed: pear.corneltek.com
file_get_contents(http://pear.corneltek.com/channel.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

PEAR Channel discover failed: pear.corneltek.com
file_get_contents(http://pear.corneltek.com/channel.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

PEAR Channel discover failed: pear.corneltek.com
file_get_contents(http://pear.corneltek.com/channel.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

EPEAR Channel discover failed: pear.corneltek.com
file_get_contents(http://pear.corneltek.com/channel.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

PEAR Channel discover failed: pear.corneltek.com
file_get_contents(http://pear.corneltek.com/channel.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

PEAR Channel discover failed: pear.corneltek.com
file_get_contents(http://pear.corneltek.com/channel.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

E.--2018-01-22 22:40:01--  http://pear.corneltek.com/get/AssetKit-1.4.1.tgz
Resolving pear.corneltek.com (pear.corneltek.com)... 106.186.115.174
Connecting to pear.corneltek.com (pear.corneltek.com)|106.186.115.174|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-22 22:40:02 ERROR 404: Not Found.

E
Using temp dir: /var/folders/p3/lkw0cgjj2fq0656q_9rd0mk80000gn/T/pearx_tests
  1 Fetch␣data␣lazily¬
--2018-01-22 22:40:02--  http://pear.corneltek.com/get/CLIFramework-1.5.7.tgz
Resolving pear.corneltek.com (pear.corneltek.com)... 106.186.115.174
Connecting to pear.corneltek.com (pear.corneltek.com)|106.186.115.174|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-22 22:40:03 ERROR 404: Not Found.

E
Using temp dir: /var/folders/p3/lkw0cgjj2fq0656q_9rd0mk80000gn/T/pearx_tests
..........                                                18 / 18 (100%)

Time: 8.9 seconds, Memory: 20.00MB

There were 4 errors:

1) ChannelTest::testPackageFindWithFileSystemCache
Exception: channel.xml fetch failed.

/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:168
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:247
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:89
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:183
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:228
/Users/tfidry/Project/phpbrew/PEARX/tests/PEARX/ChannelTest.php:51

2) ChannelTest::testChannel with data set #0 ('pear.corneltek.com')
Exception: channel.xml fetch failed.

/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:168
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:247
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Channel.php:89
/Users/tfidry/Project/phpbrew/PEARX/tests/PEARX/ChannelTest.php:79

3) InstallerTest::testPearPackageInstaller with data set #0 ('http://pear.corneltek.com/get....1.tgz')
InvalidArgumentException: Invalid argument, /private/var/folders/p3/lkw0cgjj2fq0656q_9rd0mk80000gn/T/pearx_tests/AssetKit-1.4.1.tgz cannot be found

/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Installer.php:69
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Installer.php:40
/Users/tfidry/Project/phpbrew/PEARX/tests/PEARX/InstallerTest.php:34

4) InstallerTest::testPearPackageInstaller with data set #1 ('http://pear.corneltek.com/get....7.tgz')
InvalidArgumentException: Invalid argument, /private/var/folders/p3/lkw0cgjj2fq0656q_9rd0mk80000gn/T/pearx_tests/CLIFramework-1.5.7.tgz cannot be found

/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Installer.php:69
/Users/tfidry/Project/phpbrew/PEARX/src/PEARX/Installer.php:40
/Users/tfidry/Project/phpbrew/PEARX/tests/PEARX/InstallerTest.php:34
```

Although I made sure the same number of errors was happening before and after the change.

### CODE REVIEW

**Comment by theofidry** [comment]
ping @c9s

If there's anything you're not happy with in the PR please feel free to say so, I'll change it ASAP

**Comment by c9s** [comment]
Sorry i missed the mail. Could you see what cause travis ci build fail?

**Comment by c9s** [comment]
@theofidry

**Comment by theofidry** [comment]
No problem.

The failures appear to be due to the file no longer existing on that
website, is there an alternative file we could use for the tests? Even
better maybe we could keep an instance of the file and mock the HTTP call?

**Comment by c9s** [comment]
Looks like .travis-ci.yml is missing lol.   let me merge the PR first.

**Comment by c9s** [comment]
Thanks for your work!

**Comment by theofidry** [comment]
You're welcome, and thanks for phpbrew it's a life-saver :)

**Comment by c9s** [comment]
Glad you like it ;)

Théo FIDRY <notifications@github.com>於 2018年2月5日 週一，15:06寫道：

**Pull request merged**
